
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "54320:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
